#!/bin/bash

# todo 账户创建后，其他配置可使用aliyun openapi自动化
# 准备工作(aliyun控制台)
# 1. 在组织运营VPC中，添加一个附加网段(10.11.0.0/16)并追加两个交换机(10.11.0.0/24, 10.11.1.0/24)，集群egress节点放在这两个交换机下
# 2. ECS IT所在安全组规则，VPC上面的附加网段内开放ICMP。在组织运营VPC中创建一个NAT网关及一个EIP并绑定，作为集群出口网关。为上述两个交换机网段分别配置SNAT
# 3. 创建新的路由表绑定附加交换机，创建自定义路由条目: 0.0.0.0/0 -> NAT网关，egress节点可访问公网，原默认路由表更名为主交换机路由表
# 4. 在组织运营VPC中创建一个NAS文件系统Cluster NAS，使用通用-性能规格，用于集群存储
# 5. 创建托管ACK Pro集群，<组织名>-cluster-<地域>-production:
#   5.1 集群配置: 使用Flanned网络插件2个主交换机，节点Pod数量128个，Pod和Service CIDR分别为172.16.0.0/12，192.168.0.0/16。取消配置SNAT，不使用EIP暴露API Server。时区使用UTC
#   5.2 节点配置: 节点池名称cluster-manage-minimal，价格由低到高选择磁盘兼容的所有节点规格，节点数1个并添加一个200G的数据盘，操作系统默认并使用已有密钥对。添加节点标签<组织域名>/cluster-manage: minimal，自定义节点名称worker- -cluster-manage-minimal
#   5.3 组件配置: 不安装Ingress，不创建NAS文件系统，不启用监控，日志和控制平面组件日志。组件增加ACK-Virtual-Node，ack-kruise，配置Cloud Controller Manager的routeTableIDs为VPC的主、附加交换机路由表ID
# 6. 集群创建的安全组规则，未workbench网段(100.104.0.0/16)开放22端口。修改节点池付费为包年包月，配置启动集群自动弹性伸缩，弹性灵敏度15s。连接信息中将集群凭证复制到IT ECS服务器的~/.kube/config文件中


# 2. 创建名为operator@组织域名的RAM用户并授予管理员权限；为组织创建api RAM用户，授予DNS权限(用于cert-manager的DNS01校验)
# 3. 创建组织级资源组，每个运营/集成地域分别创建VPC专网和交换机(每个可用区一个)
# 4. 运营/集成地域每个VPC内分别创建私网DNS: prod/intgr.it.组织域名(如ouxxa.com)
# 5. 每个组织VPC内创建NAS文件系统IT NAS，用于组织级IT服务器存储VPN网关配置和代理仓库数据
# 6. 为组织创建OSS存储桶，用于组织级软件包存储和下载
# 7. 每个组织VPC中创建ECS(4 * 16 + 40)，实例名为"组织名-IT"，将IT NAS文件系统挂载到/opt目录。创建私网DNS解析到服务器私网IP
# 8. 每个组织VPC中添加自定义路由条目，名为"自建NAT网关"，0.0.0.0/0 下一跳为ECS IT服务器
# 9. 调整ECS所在安全组规则，VPC网段内开放ICMP(IPv4)以及22、80、443端口，workbench网段(100.104.0.0/16)开放22端口，完全开放(0.0.0.0/0)1194端口，全部是TCP
# 10. 使用workbench进入ECS IT终端命令行(内网IP)，执行安装脚本自建NAT网关、OPENVPN网关、证书管理区和代理仓库(nginx + nexus3)

echo "#####################################################"
echo "## Start -- 开始安装(aliyun ack cluster for production)"
echo "######################################################"