---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aliyun-${middleware}-initializer
  namespace: ${namespace}
data:
  initializer.js: |
    ${program}
  initializer.yaml: |
    ${config}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aliyun-${middleware}-initializer
  namespace: ${namespace}
  labels:
    app.kubernetes.io/name: aliyun-${middleware}-initializer
    app.kubernetes.io/instance: aliyun-${middleware}-initializer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aliyun-${middleware}-initializer
      app.kubernetes.io/instance: aliyun-${middleware}-initializer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aliyun-${middleware}-initializer
        app.kubernetes.io/instance: aliyun-${middleware}-initializer
      annotations: {}
    spec:
      initContainers:
        - name: npm-installer
          image: node:18
          command:
          - /bin/bash
          - -c
          - |
            cd /aliyun/${middleware}
            npm install ${middleware-sdk} @alicloud/openapi-client @alicloud/tea-util @alicloud/tea-typescript js-yaml
          volumeMounts:
            - mountPath: /aliyun/${middleware}/node_modules
              name: node-modules
      containers:
        - name: nodejs
          image: node:18
          imagePullPolicy: IfNotPresent
          command:
          - /bin/bash
          - -c
          - |
            node /aliyun/${middleware}/initializer.js
          env:
          - name: ALIBABA_CLOUD_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aliyun-secret
                key: access-key
          - name: ALIBABA_CLOUD_ACCESS_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: aliyun-secret
                key: secret-key
          resources:
            requests:
              cpu: 500m
              memory: 1G
          volumeMounts:
            - mountPath: /aliyun/${middleware}
              name: ${middleware}-initializer
              readOnly: true
            - mountPath: /aliyun/${middleware}/node_modules
              name: node-modules
      volumes:
        - name: ${middleware}-initializer
          configMap:
            name: aliyun-${middleware}-instance
            defaultMode: 0755
        - name: node-modules
          emptyDir: {}